# Learning Management System

###
# group: local / students
# @name All
GET localhost:8080/students
Authorization: Basic user password

###
# group: local / students
# @name By id
GET localhost:8080/students/5a231280-1988-410f-98d9-852b8dc9caf1
Authorization: Basic user password

###
# group: local / students
# @name Create
POST localhost:8080/students
Authorization: Basic user password
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Testov",
  "email": "test@gmail.com",
  "dateOfBirth": "2010-05-13",
  "coins": 1004.00,
  "locale": "en"
}

###
# group: local / students
# @name Add course
POST localhost:8080/students/5a231280-1988-410f-98d9-852b8dc9caf1/courses/b902261b-d1b9-4c58-869f-b04a5bbff4c9
Authorization: Basic user password

###
# group: local / students
# @name Update by id
PUT localhost:8080/students/5a231280-1988-410f-98d9-852b8dc9caf1
Authorization: Basic user password
Content-Type: application/json

{
  "firstName": "A",
  "lastName": "B",
  "email": "email@gmail.com",
  "dateOfBirth": "2005-07-23",
  "coins": 1448.00,
  "locale": "ru",
  "courseIds": [
    "b902261b-d1b9-4c58-869f-b04a5bbff4c9"
  ]
}

###
# group: local / students
# @name By id
DELETE localhost:8080/students/5a231280-1988-410f-98d9-852b8dc9caf1
Content-Type: text/plain

{
    "firstName": "Test",
    "lastName": "Testov",
    "email": "test@gmail.com",
    "dateOfBirth": "2010-05-13",
    "coins": 1004.00
}

###
# group: local / courses
# @name All
GET localhost:8080/courses
Authorization: Basic user password

###
# group: local / courses
# @name By id
GET localhost:8080/courses/64852c52-ed64-4438-b095-2ca10f6b4be0
Authorization: Basic user password

###
# group: local / courses
# @name Create
POST localhost:8080/courses
Authorization: Basic user password
Content-Type: application/json

{
  "title": "Test course 6",
  "description": "No description needed",
  "price": 100.00,
  "coinsPaid": 100.00
}

###
# group: local / courses
# @name Update by id
PUT localhost:8080/courses/fdcdaf74-8c4d-442f-bc1e-1ab6f4ddb8ee
Authorization: Basic user password
Content-Type: application/json

{
  "title": "Test course 10",
  "description": "No description needed",
  "price": 100.00,
  "coinsPaid": 100.00,
  "courseSettingsId": "b3fd0738-24af-4eea-99f5-5e81bff1500b",
  "studentIds": [
    "5a231280-1988-410f-98d9-852b8dc9caf1"
  ]
}

###
# group: local / courses
# @name By id
DELETE localhost:8080/courses/f74405a1-25e9-4b19-b366-bf4be157d138
Content-Type: text/plain

{
    "firstName": "Test",
    "lastName": "Testov",
    "email": "test@gmail.com",
    "dateOfBirth": "2010-05-13",
    "coins": 1004.00
}

###
# group: local / lessons
# @name All
GET localhost:8080/lessons
Authorization: Basic user password

###
# group: local / lessons
# @name By id
GET localhost:8080/lessons/e21d011a-c987-4ebc-90cd-2416a6730acd
Authorization: Basic user password

###
# group: local / lessons
# @name Create VideoLesson
POST localhost:8080/lessons
Authorization: Basic user password
Content-Type: application/json

{
  "type": "VIDEO",
  "title": "I don't know",
  "durationInMinutes": 80,
  "url": "https:haha.com",
  "platform": "Zoom"
}

###
# group: local / lessons
# @name Create ClassroomLesson
POST localhost:8080/lessons
Authorization: Basic user password
Content-Type: application/json

{
  "type": "CLASSROOM",
  "title": "I don't know",
  "durationInMinutes": 80,
  "location": "Belarus",
  "capacity": 88
}

###
# group: local / lessons
# @name Update VideoLesson by id
PUT localhost:8080/lessons/d21deae0-0eaa-41fe-b08d-5dce5b9e96e1
Authorization: Basic user password
Content-Type: application/json

{
  "type": "VIDEO",
  "title": "I don't know",
  "durationInMinutes": 90,
  "url": "https:haha.com",
  "platform": "Zoom",
  "courseId": "64852c52-ed64-4438-b095-2ca10f6b4be0"
}

###
# group: local / lessons
# @name Update ClassroomLesson by id
PUT localhost:8080/lessons/8763e9a3-9544-4837-862a-772f0796fa01
Authorization: Basic user password
Content-Type: application/json

{
  "type": "CLASSROOM",
  "title": "I don't know",
  "durationInMinutes": 70,
  "capacity": 45,
  "location": "Minsk",
  "courseId": "64852c52-ed64-4438-b095-2ca10f6b4be0"
}

###
# group: local / lessons
# @name By id
DELETE localhost:8080/lessons/373e60bb-c872-4207-982c-859b4dfdb4f7
Content-Type: text/plain

{
    "firstName": "Test",
    "lastName": "Testov",
    "email": "test@gmail.com",
    "dateOfBirth": "2010-05-13",
    "coins": 1004.00
}

###
# group: local / course-settings
# @name All
GET localhost:8080/course-settings
Authorization: Basic user password

###
# group: local / course-settings
# @name By id
GET localhost:8080/course-settings/38811913-ce40-4ef4-a596-f24d94356949
Authorization: Basic user password

###
# group: local / course-settings
# @name Create
POST localhost:8080/course-settings
Authorization: Basic user password
Content-Type: application/json

{
  "startDate": "2025-06-01 23:59:59",
  "endDate": "2025-06-04 20:00:00",
  "isPublic": true
}

###
# group: local / course-settings
# @name Update by id
PUT localhost:8080/course-settings/201a2493-356e-42ef-b668-fdd76f457d93
Authorization: Basic manager password
Content-Type: application/json

{
  "startDate": "2025-06-01 23:59:59",
  "endDate": "2025-06-04 20:00:00",
  "isPublic": false
}

###
# group: local / course-settings
# @name By id
DELETE localhost:8080/course-settings/8118c118-a57b-4c0e-94e4-975217b712b9
Content-Type: text/plain

{
    "firstName": "Test",
    "lastName": "Testov",
    "email": "test@gmail.com",
    "dateOfBirth": "2010-05-13",
    "coins": 1004.00
}

###
# group: local / actuator
# @name info
GET localhost:8080/actuator/info
Authorization: Basic manager password

###
# group: local / actuator
# @name health
GET localhost:8080/actuator/health

###
# group: local / actuator
# @name loggers
GET localhost:8080/actuator/loggers
Authorization: Basic manager password

###
# group: cloud / students
# @name All
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/students
Authorization: Bearer
###
# group: cloud / students
# @name By id
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/students/5a231280-1988-410f-98d9-852b8dc9caf1
Authorization: Bearer
###
# group: cloud / students
# @name Create
POST https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/students
Authorization: Bearer
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Testov",
  "email": "test@gmail.com",
  "dateOfBirth": "2010-05-13",
  "coins": 1004.00
}

###
# group: cloud / students
# @name Add course
POST https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/students/5a231280-1988-410f-98d9-852b8dc9caf1/courses/f74405a1-25e9-4b19-b366-bf4be157d138
Authorization: Bearer
###
# group: cloud / students
# @name Update by id
PUT https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/students/5a231280-1988-410f-98d9-852b8dc9caf1
Authorization: Bearer
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Updated",
  "email": "test@gmail.com",
  "dateOfBirth": "2010-05-13",
  "coins": 500.00
}

###
# group: cloud / students
# @name By id
DELETE https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/students/5a231280-1988-410f-98d9-852b8dc9caf1
Authorization: Bearer
Content-Type: text/plain

{
    "firstName": "Test",
    "lastName": "Testov",
    "email": "test@gmail.com",
    "dateOfBirth": "2010-05-13",
    "coins": 1004.00
}

###
# group: cloud / courses
# @name All
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/courses
Authorization: Bearer
###
# group: cloud / courses
# @name By id
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/courses/f74405a1-25e9-4b19-b366-bf4be157d138
Authorization: Bearer
###
# group: cloud / courses
# @name Create
POST https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/courses
Content-Type: application/json

{
  "title": "Test course 6",
  "description": "No description needed",
  "price": 100.00,
  "coinsPaid": 100.00
}

###
# group: cloud / courses
# @name Update by id
PUT https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/courses/f74405a1-25e9-4b19-b366-bf4be157d138
Content-Type: application/json

{
  "title": "Test course 10",
  "description": "No description needed",
  "price": 100.00,
  "coinsPaid": 100.00,
  "courseSettingsId": "b3fd0738-24af-4eea-99f5-5e81bff1500b"
}

###
# group: cloud / courses
# @name By id
DELETE https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/courses/f74405a1-25e9-4b19-b366-bf4be157d138
Content-Type: text/plain

{
    "firstName": "Test",
    "lastName": "Testov",
    "email": "test@gmail.com",
    "dateOfBirth": "2010-05-13",
    "coins": 1004.00
}

###
# group: cloud / lessons
# @name All
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/lessons

###
# group: cloud / lessons
# @name By id
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/lessons/373e60bb-c872-4207-982c-859b4dfdb4f7

###
# group: cloud / lessons
# @name Create VideoLesson
POST https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/lessons
Content-Type: application/json

{
  "type": "VIDEO",
  "title": "I don't know",
  "durationInMinutes": 80,
  "url": "https:haha.com",
  "platform": "Zoom"
}

###
# group: cloud / lessons
# @name Create ClassroomLesson
POST https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/lessons
Content-Type: application/json

{
  "type": "CLASSROOM",
  "title": "I don't know",
  "durationInMinutes": 80,
  "location": "Belarus",
  "capacity": 88
}

###
# group: cloud / lessons
# @name Update VideoLesson by id
PUT https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/lessons/373e60bb-c872-4207-982c-859b4dfdb4f7
Authorization: Bearer
Content-Type: application/json

{
  "type": "VIDEO",
  "title": "I don't know",
  "durationInMinutes": 180,
  "url": "https:haha.com",
  "platform": "Zoom"
}

###
# group: cloud / lessons
# @name Update ClassroomLesson by id
PUT https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/lessons/373e60bb-c872-4207-982c-859b4dfdb4f7
Authorization: Bearer
Content-Type: application/json

{
  "type": "CLASSROOM",
  "title": "I don't know",
  "durationInMinutes": 180,
  "url": "https:haha.com",
  "platform": "Zoom"
}

###
# group: cloud / lessons
# @name By id
DELETE https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/lessons/373e60bb-c872-4207-982c-859b4dfdb4f7
Content-Type: text/plain

{
    "firstName": "Test",
    "lastName": "Testov",
    "email": "test@gmail.com",
    "dateOfBirth": "2010-05-13",
    "coins": 1004.00
}

###
# group: cloud / course-settings
# @name All
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/course-settings
Authorization: Bearer
###
# group: cloud / course-settings
# @name By id
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/course-settings/8118c118-a57b-4c0e-94e4-975217b712b9
Authorization: Bearer
###
# group: cloud / course-settings
# @name Create
POST https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/course-settings
Authorization: Bearer
Content-Type: application/json

{
  "startDate": "2025-06-01 23:59:59",
  "endDate": "2025-06-04 20:00:00",
  "isPublic": true
}

###
# group: cloud / course-settings
# @name Update by id
PUT https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/course-settings/34b56d95-5d74-44b1-b473-3ab2fd36cc5f
Authorization: Bearer
Content-Type: application/json

{
  "startDate": "2025-05-29 23:59:59",
  "endDate": "2025-06-04 20:00:00",
  "isPublic": false
}

###
# group: cloud / course-settings
# @name By id
DELETE https://learning-management-system-bright-vicuna-rd.cfapps.us10-001.hana.ondemand.com/course-settings/8118c118-a57b-4c0e-94e4-975217b712b9
Content-Type: text/plain

{
    "firstName": "Test",
    "lastName": "Testov",
    "email": "test@gmail.com",
    "dateOfBirth": "2010-05-13",
    "coins": 1004.00
}

###
# group: cloud / actuator
# @name info
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/actuator/info
Authorization: Basic manager password

###
# group: cloud / actuator
# @name health
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/actuator/health
Authorization: Basic manager password

###
# group: cloud / actuator
# @name loggers
GET https://067769ebtrial-dev-learning-management-system.cfapps.us10-001.hana.ondemand.com/actuator/loggers
Authorization: Basic manager password

###
# group: sap-services / destination-service
# @name Request token
POST https://067769ebtrial.authentication.us10.hana.ondemand.com/oauth/token
Authorization: Bearer
Content-Type: application/x-www-form-urlencoded

grant_type = client_credentials

###
# group: sap-services / destination-service
# @name Get destination
GET https://destination-configuration.cfapps.us10.hana.ondemand.com/destination-configuration/v1/destinations/SmtpDestination
Authorization: Bearer
###
# group: sap-services / xsuaa
# @name Request token
POST https://067769ebtrial.authentication.us10.hana.ondemand.com/oauth/token
Authorization: Basic
Content-Type: application/x-www-form-urlencoded

grant_type = client_credentials