info:
  app:
    name: Learning Managements System
    description: Application provides functionality for creation of courses and students' further enrollment
    version: @project.version@

spring:
  application:
    name: LearningManagementSystem
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
