spring:
  datasource:
    url: ${vcap.services.hana-schema.credentials.url}
    username: ${vcap.services.hana-schema.credentials.user}
    password: ${vcap.services.hana-schema.credentials.password}
    driver-class-name: com.sap.db.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.HANAColumnStoreDialect

feature-flags:
  uri: ${vcap.services.feature-flags-service.credentials.uri}
  username: ${vcap.services.feature-flags-service.credentials.username}
  password: ${vcap.services.feature-flags-service.credentials.password}

destination:
  url: ${vcap.services.destination-service.credentials.url}
  uri: ${vcap.services.destination-service.credentials.uri}
  clientId: ${vcap.services.destination-service.credentials.clientid}
  clientSecret: ${vcap.services.destination-service.credentials.clientsecret}

user-provided:
  mail:
    smtp:
      from: ${vcap.services.user-service.credentials.mail.smtp.from}
      host: ${vcap.services.user-service.credentials.mail.smtp.host}
      port: ${vcap.services.user-service.credentials.mail.smtp.port}
      protocol: ${vcap.services.user-service.credentials.mail.transport.protocol}
      password: ${vcap.services.user-service.credentials.mail.smtp.password}

xsuaa:
  url: ${vcap.services.xsuaa-service.credentials.url}
  clientId: ${vcap.services.xsuaa-service.credentials.clientid}
  clientSecret: ${vcap.services.xsuaa-service.credentials.clientsecret}

service-manager:
  url: ${vcap.services.service-manager.credentials.url}
  smUrl: ${vcap.services.service-manager.credentials.sm_url}
  clientId: ${vcap.services.service-manager.credentials.clientid}
  clientSecret: ${vcap.services.service-manager.credentials.clientsecret}

application:
  applicationId: ${vcap.application.application_id}
  spaceId: ${vcap.application.space_id}
  uri: ${vcap.application.uris[0]}

security-entity:
  user:
    username: user
    password: password
  manager:
    username: manager
    password: password
  admin:
    username: admin
    password: password