spring:
  datasource:
    username: user
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: tikva838@gmail.com
    password: isbg brui uwfp ixdl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false