databaseChangeLog:
  - changeSet:
      id: insert-course_settings-table
      author: Mikita Shapel
      changes:
        - insert:
            tableName: course_settings
            columns:
              - column:
                  name: id
                  value: '38811913-ce40-4ef4-a596-f24d94356949'
              - column:
                  name: start_date
                  valueDate: '2025-05-13 09:30:00'
              - column:
                  name: end_date
                  value: '2025-06-23 15:00:00'
              - column:
                  name: is_public
                  value: true
        - loadData:
            file: data/course_settings.csv
            tableName: course_settings
            separator: ","
            encoding: UTF-8